export default {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    VERIFY: "VERIFY",
    PRODUCT: "PRODUCT",
    CATEGORIES: 'CATEGORIES',
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
    BRAND:"BRAND",
}